pipeline {
agent any
environment {
    JAVA_HOME="C:\Users\PP116866\Downloads\jdk-17.0.12\bin"
  }
stages {
stage('Clean stage') {
steps {
dir("StockApp") {
bat 'C:\Users\PP116866\Downloads\apache-maven-3.9.9-bin\apache-maven-3.9.9\bin\mvn clean'
}
}
}

stage('Compile stage') {
steps {
dir("StockApp") {
bat 'C:\Users\PP116866\Downloads\apache-maven-3.9.9-bin\apache-maven-3.9.9\bin\mvn compile'
}
}
}

stage('Install stage') {
steps {
dir("StockApp") {
bat 'C:\Users\PP116866\Downloads\apache-maven-3.9.9-bin\apache-maven-3.9.9\bin\mvn install'
}
}
}

}
}
